export const THEME_TOGGLE = 'THEME_TOGGLE';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_SUPERSTAKERS_BEGIN = 'FETCH_SUPERSTAKERS_BEGIN';
export const FETCH_SUPERSTAKERS_SUCCESS = 'FETCH_SUPERSTAKERS_SUCCESS';
export const FETCH_SUPERSTAKERS_FAIL = 'FETCH_SUPERSTAKERS_FAIL';
export const FETCH_SUPERSTAKERS_IDLE = 'FETCH_SUPERSTAKERS_IDLE';

export const SET_ACCOUNT = 'SET_ACCOUNT';
