export const THEME_TOGGLE = 'THEME_TOGGLE';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_SUPERSTAKERS_BEGIN = 'FETCH_SUPERSTAKERS_BEGIN';
export const FETCH_SUPERSTAKERS_SUCCESS = 'FETCH_SUPERSTAKERS_SUCCESS';
export const FETCH_SUPERSTAKERS_FAIL = 'FETCH_SUPERSTAKERS_FAIL';
export const FETCH_SUPERSTAKERS_IDLE = 'FETCH_SUPERSTAKERS_IDLE';

export const FETCH_CONTRACT_BEGIN = 'FETCH_CONTRACT_BEGIN';
export const FETCH_CONTRACT_SUCCESS = 'FETCH_CONTRACT_SUCCESS';
export const FETCH_CONTRACT_FAIL = 'FETCH_CONTRACT_FAIL';
export const FETCH_CONTRACT_IDLE = 'FETCH_CONTRACT_IDLE';
